### ISSUE TITLE
Studio image drag-and-drop broken since `v4.21.0`

### ISSUE THREAD

**Issue by leeuwd** [sanity-io/sanity#11481]
**Describe the bug**

Drag-and-drop is no longer working for me since Sanity Studio [`v4.21.0`](https://github.com/sanity-io/sanity/tree/v4.21.0). The images field registers the drag action, but upon drop, nothing happens:

![Image](https://github.com/user-attachments/assets/cb8ad5a8-116e-4402-b323-99011828e625)

It worked fine in the versions before (e.g. `v4.20.3`)

**To Reproduce**

My images field definition:

```ts
export const imagesField = defineField({
  name: 'images',
  title: 'Images',
  description: imagesFieldDescription,
  type: 'array',
  of: [
    defineArrayMember({
      type: 'image',
      options: {
        accept: '.jpg, .jpeg, .png, .gif',
      },
    }),
  ],
  options: {
    layout: 'grid',
  },
  validation: (rule) => rule.unique(),
})
```

**Expected behavior**

An uploaded image.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)             4.21.0 (latest: 4.21.1)
@sanity/assist                    5.0.2 (up to date)
@sanity/color-input               5.0.4 (up to date)
@sanity/dashboard                 5.0.0 (up to date)
@sanity/google-maps-input         4.2.0 (up to date)
@sanity/orderable-document-list   1.4.0 (up to date)
@sanity/table                     2.0.0 (up to date)
@sanity/ui                       3.1.11 (up to date)
@sanity/vision                   4.21.1 (up to date)
sanity                           4.21.0 (latest: 4.21.1)
```

**What operating system are you using?**

```
macOS 26.1
```

**Which versions of Node.js / npm are you running?**

```
10.9.4
v22.21.1
```

**Comment by leeuwd** [comment]
I've found the issue!

My config to allow-list only certain filetypes (`accept: '.jpg, .jpeg, .png, .gif'`) always worked but after `v4.21.0`, this seems to be no longer supported and thus gives a silent failure.

Per latest image drag-and-drop [documentation](https://www.sanity.io/docs/studio/image-type#beb68f848c26), one needs to specify MIME-types:

```ts
defineArrayMember({
   type: 'image',
      options: {
        accept: 'image/jpeg, image/png, image/gif',
      },
}),
```

**Comment by skogsmaskin** [comment]
Thank you for reporting @leeuwd, we are on it!

**Comment by bjoerge** [comment]
Fixed in [v5.0.1.](https://github.com/sanity-io/sanity/releases/tag/v5.0.1)

If you’re unable to either 1) upgrade to v5 or 2) work around this by switching to MIME types, we’d love to understand why, and we can consider backporting this fix to v4.

**Comment by marcinincreo** [comment]
This is still a problem when using custom image types in arrays. So having:
```js
export const imageWithAlt = defineType({
  name: 'imageWithAlt',
  type: 'image',
  title: 'Image',
})

export const post = defineType({
  name: 'post',
  title: 'Post',
  type: 'document',
  fields: [
    defineField({
      name: 'layout',
      title: 'Content',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'imageWithAlt',
        }),
      ],
    }),
  ],
})
```

gives 
```
The following item can't be uploaded because there's no known conversion from content type to array item:
imageNameHere.jpeg (image/jpeg)
```

**Comment by skogsmaskin** [comment]
> This is still a problem when using custom image types in arrays. 

Yeah, we found a bug here @marcinincreo. Patch is on it's way. Thank you for reporting.

**Comment by marcinincreo** [comment]
@skogsmaskin testes now and I can confirm it is fixed in `5.1.0`.

**Comment by skogsmaskin** [comment]
That's great @marcinincreo, thanks for confirming.
