### ISSUE TITLE
Can't login on mobile (Safari  or Chrome)

### ISSUE THREAD

**Issue by danielvanc** [sanity-io/sanity#1231]
**Steps to reproduce the behavior:**
1. Go to the login of a sanity desk
2. Click on the accept cookie
3. Click to login with GitHub. After authenticated, it takes you back to which thing to login with. Click github again, and it just takes you back to what to login to. So it's re-repeating itself.

**Expected behavior**
 To login and edit where needed. 

**Which versions of Sanity are you using?**
@sanity/base             0.140.9
@sanity/components      0.140.9
@sanity/core            0.140.9
@sanity/default-layout  0.140.9
@sanity/desk-tool       0.140.9

**What operating system are you using?**
iOS 12

My settings for Safari allows cookies
![img_0384](https://user-images.githubusercontent.com/310698/54036278-28bdf580-41b3-11e9-9321-da3161ee15b3.jpg)

**Comment by danielvanc** [comment]
Haven't heard anything back on this yet? Can someone please look into it please? Quite frustrating that it's not working as a big part of the reason moving to Sanity was that I wanted to edit content on my mobile.

Thanks!

**Comment by evenwestvang** [comment]
Thanks for the report and apologies for the radio silence. We're aware of the issue. It seems that our login at times triggers the cross-site tracking prevention in Safari (even if no such tracking is going on). It's a sporadic error, but once it strikes it's sticky and prevents login.

We will definitely be addressing the issue. The immediate remedy is to allow cross-site tracking.

**Comment by danielvanc** [comment]
Thank you for the quick reply @evenwestvang and for addressing the issue! Have allowed cross-site tracking now in Safari and is working nicely, so am happy until this can be looked into. 👍

**Comment by asundlihardig** [comment]
Are there any updates on this?

**Comment by ryanscherler** [comment]
Looks like the latest version of content studio is not letting me login via Safari - looks like a cookie issue? (404) https://lx67wdtx.api.sanity.io/v1/auth/testCookie
<img width="542" alt="Screen Shot 2019-06-26 at 4 18 52 PM" src="https://user-images.githubusercontent.com/881938/60221355-32d13600-982e-11e9-9439-4d2d2fd88c14.png">

**Comment by kmelve** [comment]
This proves to be a complex issue to handle, but we are working on it! Stay tuned.

**Comment by danielvanc** [comment]
Thanks @kmelve, appreciate that. Good to hear you're still on it 👍

**Comment by fishintaiwan** [comment]
Was able to get around this in Chrome Beta by turning off the "Block third-party cookies" option in settings. Need to do this each time I want to login (since I don't plan on leaving it disabled for general browsing).

**Comment by EricWVGG** [comment]
any news on this?

**Comment by eivindml** [comment]
This doesn't happen for me anymore in the latest Safari 14 for macOS Big Sur. 🥳

<img width="396" alt="Skjermbilde 2020-09-08 kl  16 12 00" src="https://user-images.githubusercontent.com/202450/92487825-0e246c80-f1ee-11ea-8062-677393ae7984.png">

But still happens for apps (here Panic's Nova editor) using `WKWebView`.

<img width="1148" alt="Skjermbilde 2020-09-08 kl  16 08 19" src="https://user-images.githubusercontent.com/202450/92487969-3e6c0b00-f1ee-11ea-8c9e-32af861564c0.png">

**Comment by john-rock** [comment]
Anyone make progress on this? Would be a game changing feature.

**Comment by eivindml** [comment]
Yeah, it blocks some of my workflows, and confuses some of my clients who uses Safari 🥲

**Comment by simen** [comment]
We have been in dialog with browser vendors and have decided on a a definitive way to handle this. Will update this issue once release is imminent.

**Comment by jamesryan-dev** [comment]
still present issue?

**Comment by jonathanphz** [comment]
Not sure if this is the same issue but we keep getting logged out when previewing a document and it only happens in Safari.

**Comment by jonjahr** [comment]
For me, when I deploy the CMS to `<your-site>.sanity.studio`, the login works in Chrome and Safari.  When I deploy the CMS anywhere else (ie. localhost or Netlify), login doesn't work on any browser with default settings, but it works in Chrome after I enable 3rd party cookies.

**Comment by issa-me-sush** [comment]
had the same issue on brave, had to let all cookies pass through

**Comment by eivindml** [comment]
Still there in Safari. 

<img width="350" alt="Skjermbilde 2022-02-15 kl  09 19 10" src="https://user-images.githubusercontent.com/202450/154021188-443520de-13ae-4dd7-ac9b-3794c8cfb3c9.png">
<img width="425" alt="Skjermbilde 2022-02-15 kl  09 19 16" src="https://user-images.githubusercontent.com/202450/154021192-9b0fe12d-0062-46d5-8f11-176fb1706a8c.png">

**Comment by kmelve** [comment]
Hi all! We're actively working to solve this problem, and hopefully, we'll have something for you to try out soon. Stay tune!

**Comment by rexxars** [comment]
This should be solved as of [v2.28.0](https://github.com/sanity-io/sanity/releases/tag/v2.28.0)! 🎉

**Comment by emmalevesque** [comment]
I'm experiencing a similar issue, I've opened a [new issue](https://github.com/sanity-io/sanity/issues/3252), but it hasn't gotten much attention and I'm wondering if it's related to this issue?

**Comment by dallmo** [comment]
the issue still exists on both safari and brave browser.
i just finished building a starter project, and confirmed the URL to sanity studio is included in the CORS config.

in safari, that "couldn't log you in / accept cookie" thing pops up, accepted but go no further.

in brave, it just get that login loop without saying anything, no error code / no clue.
