### ISSUE TITLE
Error in using sanity init: [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string

### ISSUE THREAD

**Issue by hangindev** [sanity-io/sanity#1361]
**Describe the bug**

Cannot initialize sanity project using `sanity init` using @sanity/cli. After selecting a project template, there is an error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at require (C:/Users/name/AppData/Roaming/npm/node_modules/@sanity/cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at i (C:/Users/name/AppData/Roaming/npm/node_modules/@sanity/cli/bin/sanity-cli.js:826:130)
    at e.default (C:/Users/name/AppData/Roaming/npm/node_modules/@sanity/cli/bin/sanity-cli.js:6724:8611)
```

**To Reproduce**

1. `sanity init`
2. project name: sanity-blog
3. dataset name: production
4. output path: ./studio
5. select project template: Blog(or any other)

**Expected behavior**

Expect to successfully initialize a new sanity project

**Screenshots**

![cli](https://user-images.githubusercontent.com/23137243/59199761-4ee79d00-8bc9-11e9-864c-f59d75e9e2c6.jpg)

**Which versions of Sanity are you using?**

@sanity/cli  0.140.33

**What operating system are you using?**

Windows 10 Home

**Which versions of Node.js / npm are you running?**

npm 6.9.0/ node v10.14.1

**Comment by skogsmaskin** [comment]
I'm not able to reproduce this with `@sanity/cli 0.140.33` and node `10.14.1` (same as you). I am on a Mac though.  Can you please try to install sanity again? (`npm install -g @sanity/cli`, or if you use yarn `yarn global add @sanity/cli`)

**Comment by rexxars** [comment]
Could you try the latest release? v0.140.34 included a change that will either fix this error or at least hopefully yield a better error message

**Comment by nrator** [comment]
Hi, I have upgraded to `v0.140.34` but still facing the same issue. I cannot init the first time but when I ran `sanity init` in the same folder for the second time, it ran successfully.  Below is the log:

```
D:\Projects\Sanity Templates\test
λ sanity init
You're setting up a new project!
We'll make sure you have an account with Sanity.io. Then we'll
install an open-source JS content editor that connects to
the real-time hosted API on Sanity.io. Hang on.
Press ctrl + C at any time to quit.

Looks like you already have a Sanity-account. Sweet!

? Select project to use Create new project
? Informal name for your project testing
? Name of your first dataset: production
? Choose dataset visibility – this can be changed later Public (world readable)
? Output path: D:\Projects\Sanity Templates\test
? Select project template E-commerce (schema + sample data)
? Upload a sampling of products to go with your e-commerce schema? Yes
√ Bootstrapping files from template
√ Resolving latest module versions
√ Creating default project files
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at i (C:/Users/user/AppData/Roaming/npm/node_modules/@sanity/cli/bin/sanity-cli.js:826:130)
    at e.default (C:/Users/user/AppData/Roaming/npm/node_modules/@sanity/cli/bin/sanity-cli.js:6724:8611)

D:\Projects\Sanity Templates\test
λ sanity init
@sanity/core not installed in current project
Project-specific commands not available until you run `sanity install`
? The current folder contains a configured Sanity studio. Would you like to reconfigure it? Yes
The Sanity Studio in this folder will be tied to a new project on Sanity.io!
The previous project configuration will be overwritten.
We're first going to make sure you have an account with Sanity.io. Hang on.
Press ctrl + C at any time to quit.

Looks like you already have a Sanity-account. Sweet!

? Select project to use testing [dafkh7xs]
? Select dataset to use production
[..................] - Fetching packages
Success! Now what?

▪ sanity docs to open the documentation in a browser
▪ sanity manage to open the project settings in a browser
▪ sanity help to explore the CLI manual
▪ sanity start to run your studio
```

Thank you!

**Comment by haf** [comment]
Same here, failing on

```
 /*!***********************************!*\
   !*** ./lib/util/getUserConfig.js ***!
   \***********************************/
 /*! no static exports found */
 /*! all exports used */
 /*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(t,e,n){"use strict";    Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r,i=(r=n(/*! configstore */      510))&&r.__esModule?r:{default:r};const o=(process.env.SANITY_ENV||"").toLowerCase(),u={};let s=null;  var a=()=>(s||(s=new i.default(o&&"production"!==o?`sanity-${o}`:"sanity",u,{globalConfigPath:!0})),   s);e.default=a},
 /*!************************************!*\
   !*** ./lib/util/dynamicRequire.js ***!
   \************************************/
 /*! no static exports found */
 /*! all exports used */
 /*! ModuleConcatenation bailout: Module is not an ECMAScript module */function(t,e,n){"use strict";    const r=require,i=t=>{const e=r(t);return e.__esModule&&e.default?e.default:e};i.resolve=r.resolve,t.  exports=i},
```

On the last line, statement `const e=r(t)`, with `t` being an object.

macOS, following your content-marketing "blog with nextjs" blog post.

**Comment by bjoerge** [comment]
@haf I believe your issue is caused by a file stat cache issue in Node.js that got fixed in v11.14.0 (https://github.com/nodejs/node/issues/26926) - could you try upgrading node version and see if it helps?

@hangindev I'm not able to reproduce this error using node 10.14.1 and latest version of @sanity/cli (0.142.2). Is this still an issue for you?

**Comment by bjoerge** [comment]
Closing this for now. Let us know if it's still a problem.

**Comment by Alligatore3** [comment]
Ahm...unfortunately the problem persists for me too.

```
? Select project to use Create new project
? Your project name: My lavazza with Vue
Your content will be stored in a dataset that can be public or private, depending on
whether you want to query your content with or without authentication.
The default dataset configuration has a public dataset named "production".
? Use the default dataset configuration? Yes
✔ Creating dataset
? Project output path: /home/mattia/Development/sanity
? Select project template E-commerce (schema + sample data)
? Upload a sampling of products to go with your e-commerce schema? Yes
✔ Bootstrapping files from template
✔ Resolving latest module versions
✔ Creating default project files
[..................] - Fetching packages
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received null
    at i (~/.nvm/versions/node/v12.16.1/lib/node_modules/@sanity/cli/bin/sanity-cli.js:544:130)
    at e.default (~/.nvm/versions/node/v12.16.1/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4792:9580)
```

Also some details here:
```
➜  sanity node -v && npm -v
v12.16.1
6.13.4
```
`OS => Ubuntu 18.04.4 LTS`

**Comment by dardub** [comment]
I've just run into this issue as well.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received null
    at i (~/.nvm/versions/node/v14.15.3/lib/node_modules/@sanity/cli/bin/sanity-cli.js:514:130)
    at e.default (~/.nvm/versions/node/v14.15.3/lib/node_modules/@sanity/cli/bin/sanity-cli.js:4294:9604)

---


✗ node -v && npm -v
v14.15.3
6.14.9
```

I upgraded to latest lts node. Removed all the files, tried again, and it worked the second time.

**Comment by michielvanderros-tomtom** [comment]
I'm on Node 16.13, trying Sanity for the first time and also get this issue.
