### ISSUE TITLE
Improve unpublish/delete error when referenced somewhere

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity#1850]
**Is your feature request related to a problem? Please describe.**
Unpublish and delete a doc can fail with a vague error about being possibly linked somewhere.

**Describe the solution you'd like**
We should be able to unpublish or delete anything (with a warning/confirmation) and the other linked item should have a graceful fallback if it is deleted or unpublished.  This is how Contentful handles it.  The reason is a user may need to remove a page from the live site and they are basically stuck at that point if they can't unpublish or delete it.

Also, one basic rule of User Interfaces is you never leave your user hanging with nowhere to go. The message is not user friendly. At a minimum the message should at least tell you exactly what is linking to it in a friendly way and easily allow you to discover those associations and remove them to resolve the problem.

This is a real problem for me right now because I am building a workflow where documents are approved (+ published automatically) or disapproved (+ unpublished automatically) and basically a user is going to disapprove a doc and run into this error because it might be already used on the site and there is no good way around it for them.

**Describe alternatives you've considered**
Using a `published at` field is a hack around the system and is not intuitive to the published/draft model.  If I set a published at field to the future for instance to get around this issue it will show the `doc was published` message fly in which is confusion, it was disapproved but published?

**Additional context**
![image](https://user-images.githubusercontent.com/817344/80063459-d04ad400-84ea-11ea-929f-fcce9815e7f4.png)

**Comment by zanedev** [comment]
Can we at least set the `publishedAt` field to `null` in the meantime?  I tried doing that and it said invalid value for dateTime.  Now I need to filter all future dates from rendering in all my page datas?  😢

**Comment by tkdave** [comment]
"Weak" references might help here.
https://www.sanity.io/docs/reference-type#example-weak-reference-f45f659e7b28

**Comment by zanedev** [comment]
Thanks @tkdave I'll look into that!  Is there any drawback to making everything a weak reference? 

Even with using a weak reference I still feel the UI could use a better way for a regular user to resolve this and not being stuck.

**Comment by evenwestvang** [comment]
Hi Zane – that dialogue should link to the documents doing the referencing so the user can go remediate it. Marking the references as `weak` will allow deletion, but will leave you with dangling references.

**Comment by D-Pagey** [comment]
In this case, how am I supposed to delete the documents that are preventing me deleting another document?

**Comment by sebbean** [comment]
great question @D-Pagey

**Comment by tailanedebrito** [comment]
I do have the same issue as @D-Pagey asked. I already deleted the document that had the reference and now I'm actually trying to delete the Reference itself and I'm getting an error that it still linked to the one that was already deleted. Is there a way to improve this binding?

**Comment by JayBox325** [comment]
Getting this same error myself. Something to do with a draft preview referring to it.

![image](https://user-images.githubusercontent.com/13233809/200431670-a8b107c8-2551-4bbf-88d1-d726aa89078b.png)


![Screenshot 2022-11-07 at 22 47 04](https://user-images.githubusercontent.com/13233809/200431662-87f6ab42-e3b3-46b1-a610-89876c972898.png)

**Comment by ansmlc** [comment]
I have the same issue

**Comment by ansmlc** [comment]
@D-Pagey @tailanedebrito @JayBox325 

Anyone found a fix for this?

**Comment by kmelve** [comment]
Thanks for reporting! This should be fixed in newer versions of Sanity Studio.

<img width="708" alt="CleanShot 2023-01-12 at 19 31 06@2x" src="https://user-images.githubusercontent.com/1131579/212149685-1c100fd2-834f-484f-a779-7086201c842c.png">

**Comment by dbettini** [comment]
> Thanks for reporting! This should be fixed in newer versions of Sanity Studio.
> 
> <img alt="CleanShot 2023-01-12 at 19 31 06@2x" width="708" src="https://user-images.githubusercontent.com/1131579/212149685-1c100fd2-834f-484f-a779-7086201c842c.png">

Still happening. The prompt does appear, but after clicking "Delete anyway", it still shows the error:

> An error occurred while attempting to delete this document. This usually means that there are other documents that refers to it.
Details
Mutation(s) failed with 1 error(s)

**Comment by vincentjflorio** [comment]
![image](https://github.com/user-attachments/assets/2c2b98f2-02b6-4d83-b4f8-5ee12b4f478e)

We are getting something similar on 3.49; the details didn't list the places to go, and different users got a different presentation (some had the elaborate UI, some got this toast notification).

**Comment by raldea** [comment]
> > Thanks for reporting! This should be fixed in newer versions of Sanity Studio.
> > <img alt="CleanShot 2023-01-12 at 19 31 06@2x" width="708" src="https://user-images.githubusercontent.com/1131579/212149685-1c100fd2-834f-484f-a779-7086201c842c.png">
> 
> This is still happening to me, @sanity/cli version 3.9.1

I can still replicate this issue in 5.30.0
