### ISSUE TITLE
Warnings on "sanity start" after uninstalling sanity-plugin-mux-input

### ISSUE THREAD

**Issue by deodat** [sanity-io/sanity#2178]
**Describe the bug**

After uninstalling sanity-plugin-mux-input (not sure it's related), I have this warning when running `sanity start` :

```
Compiled with warnings.

Warning in ./node_modules/@sanity/ui/dist/es/atoms/icon/icon.js
16:9-14 "export 'default' (imported as 'icons') was not found in '@sanity/icons'
 @ ./node_modules/@sanity/ui/dist/es/atoms/icon/icon.js
 @ ./node_modules/@sanity/ui/dist/es/atoms/icon/index.js
 @ ./node_modules/@sanity/ui/dist/es/atoms/index.js
 @ ./node_modules/@sanity/ui/dist/es/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js

Warning in ./node_modules/@sanity/ui/dist/es/atoms/icon/icon.js
19:25-30 "export 'default' (imported as 'icons') was not found in '@sanity/icons'
 @ ./node_modules/@sanity/ui/dist/es/atoms/icon/icon.js
 @ ./node_modules/@sanity/ui/dist/es/atoms/icon/index.js
 @ ./node_modules/@sanity/ui/dist/es/atoms/index.js
 @ ./node_modules/@sanity/ui/dist/es/index.js
 @ ./node_modules/@sanity/base/lib/components/SanityRoot.js (part:@sanity/base/sanity-root)
 @ ./node_modules/@sanity/server/lib/browser/entry-dev.js
 @ multi ./node_modules/normalize.css/normalize.css ./node_modules/@sanity/server/lib/browser/entry-dev.js
```
It doesn't seem to affect anything on the Studio though.

**Which versions of Sanity are you using?**

@sanity/cli                2.0.9 (latest: 2.1.0)
@sanity/base               2.1.0 (up to date)
@sanity/components         2.1.0 (up to date)
@sanity/core               2.1.0 (up to date)
@sanity/default-layout     2.1.0 (up to date)
@sanity/default-login      2.1.0 (up to date)
@sanity/desk-tool          2.1.0 (up to date)
@sanity/google-maps-input  2.1.0 (up to date)
@sanity/structure          2.1.0 (up to date)
@sanity/vision             2.1.0 (up to date)

**What operating system are you using?**
I'm using Mac OS Big Sur (11.0.1)

**Which versions of Node.js / npm are you running?**
npm 6.14.9
node v14.11.0

**Comment by bjoerge** [comment]
Thanks for reporting! Should be fixed in [v2.1.1](https://github.com/sanity-io/sanity/releases/tag/v2.1.1). (It's not related to uninstalling the mux plugin)

**Comment by dmorda** [comment]
Just installed v2.1.1, but am still having the issue. Removed node_modules and then did a `sanity install`. But after running `sanity start` I'm still seeing the same error. Is there something else I have to do?

**Comment by deodat** [comment]
Works for me in v.2.1.2
