### ISSUE TITLE
[Improvement] Show custom views when selecting documents from search field

### ISSUE THREAD

**Issue by mornir** [sanity-io/sanity#2539]
**Is your feature request related to a problem? Please describe.**
Currently, when content editors access a document through search, the document opens in this URL:
https://xxxxxxx.sanity.studio/desk/__edit__DOC_ID%2Ctype%3Dentry
Custom views are not displayed:
![image](https://user-images.githubusercontent.com/1411843/120931616-a3f41600-c6f2-11eb-9376-2b73099cbdab.png)

**Video**
https://user-images.githubusercontent.com/1411843/120932000-4fea3100-c6f4-11eb-9e15-cd223fbaaef1.mp4

Custom views can contain important information and controls and it's quite cumbersome for content editors to manually search through the document list in order to access the custom views.

**Describe the solution you'd like**
Show the custom views in the edit view (https://xxxxxxx.sanity.studio/desk/__edit__DOC_ID%2Ctype%3Dentry), the same way as for the normal view (https://xxxxxxx.sanity.studio/desk/eintrageNachStatus;entwurf;DOC_ID)
![image](https://user-images.githubusercontent.com/1411843/120931748-3a283c00-c6f3-11eb-954c-0d373497a7ad.png)

**Comment by fabien** [comment]
Hi, are you using `getDefaultDocumentNode`? This should ensure these additional views across the Studio. See **Tabs with content previews** here: https://www.sanity.io/docs/structure-builder-typical-use-cases#a8e5cc70dbc0

**Comment by mornir** [comment]
Hey!
Yes, I'm using `getDefaultDocumentNode`.

**Comment by fabien** [comment]
I see, so it still doesn't work as expected in this case? That's odd. I'm about to use this functionality right now, and will check how it behaves and report back.

**Comment by fabien** [comment]
I can confirm that this is a bug. Going to a document via the search results will bypass the `getDefaultDocumentNode` functionality, and tabs are missing as a result.

**Comment by mornir** [comment]
Thanks for confirming it 😃

**Comment by fabien** [comment]
In addition, as a feature request: having the option to enable 'split panes' even when no custom preview components have been set would be extremely useful for scenarios involving translated content (side-by-side comparison).

**Comment by samzhao** [comment]
Seeing the same issue here.

The desk structure/nested navigation resets completely after i click on the link to a referenced document from another document. At the same time, the custom document views are no longer available.

Please see the attached screenshots.
Any pointers and help appreciated. Thanks in advance!

![image](https://user-images.githubusercontent.com/1125203/126205673-befc6b2d-6ebf-4b15-aa4f-da82f089f281.png)

![image](https://user-images.githubusercontent.com/1125203/126205682-8f8ff7c5-d6f1-4d69-a240-8eb545b48321.png)

**Comment by doigo** [comment]
+ 1 having the same issue here

**Comment by mmgj** [comment]
Yep. Me too.

**Comment by mornir** [comment]
Fixed in [v2.21.10](https://github.com/sanity-io/sanity/releases/tag/v2.21.10)! 🎉🙌🎉

**Comment by schellenbergk** [comment]
I'm on `v2.29.3` and if using singleton pages this issue still exists:

```
S.list()
            .title('Pages')
            .items([
              // These do not show tabs (only if you search for them):
              ...Object.keys(singlePages).map((k) =>
                S.listItem()
                  .title(singlePages[k])
                  .child(
                    S.editor().id(k).schemaType(k).documentId(`singleton-${k}`)
                  )
              ),
              // These show tabs
              ...S.documentTypeListItems().filter((i) =>
                [...customPages].includes(i.getId())
              ),
            ])
```
