### ISSUE TITLE
Unable to add CORS origins

### ISSUE THREAD

**Issue by ErnestBrandi** [sanity-io/sanity#2694]
**Describe the bug**

Adding a domain with a wildcard such as in the documentation: `https://*.example.org`; does not work. I get the warning: Unable to parse URL.

**To Reproduce**

Just try to add it through the panel on sanity.io (Settings > API Settings). 

**Expected behavior**

Being able to use wildcards.
Also do you plan adding regex support ? I'd like to do something a little more advanced; for instance https://mydomain-(.*)-username.vercel.app (preventing me to update CORS for all dev url generated).

**Comment by vicbergquist** [comment]
Hi! Which browser are you using?

**Comment by ErnestBrandi** [comment]
Right, this does work in Chrome but not in Firefox.

**Comment by rexxars** [comment]
This should now be solved, thanks for reporting!

**Comment by ntvangoor** [comment]
This is still an issue. 
I can't add `https://*.example.org` with Firefox. 
Though it works for me with Edge.
