### ISSUE TITLE
Invalid schema types when working with singletons in 2.21

### ISSUE THREAD

**Issue by malinowskip** [sanity-io/sanity#2869]
**Describe the bug**

I have two singletons in my new schema: `homepage` and `siteSettings`. I have added them to my Studio instance using the Structure Builder.

In 2.21, I cannot use both singletons at once, because Studio does not distinguish between them and apparently treats both as one document.

**2.19 (working as intended)**

https://user-images.githubusercontent.com/47485431/137562108-c2301c9a-29ff-42a4-94e5-071a6ef2fb6c.mov

**2.21 (wrong schema types)**

https://user-images.githubusercontent.com/47485431/137562191-0683e77f-c64e-4a67-86d1-eeec556418eb.mov

When I enter some data, publish the document and refresh, I’m getting this error:

<img width="1114" alt="Zrzut ekranu 2021-10-16 o 00 53 41" src="https://user-images.githubusercontent.com/47485431/137562480-4a594801-a468-46ee-889d-7044a662c639.png">

**Which versions of Sanity are you using?**
2.19 vs 2.21

**Comment by etuned** [comment]
I have this as well with the new update.

**Comment by malinowskip** [comment]
Yes, I initially encountered it in `2.21.4`.

**Comment by flangham** [comment]
I'm having what I presume is a related issue. When switching between singleton types, the fields don't update to reflect the new type unless I refresh the page

![image](https://user-images.githubusercontent.com/67903118/137894321-1faed2cb-3eb1-499e-b963-97a017f711e7.png)

![image](https://user-images.githubusercontent.com/67903118/137894248-a5eb9853-cb2e-449c-a720-dfa6dd7baf4e.png)

After refresh:
![image](https://user-images.githubusercontent.com/67903118/137894384-e02dbe6c-652e-4db4-accf-bb51725c849c.png)

**Comment by malinowskip** [comment]
It looks like the problem has now been resolved in `2.21.5`.

**Comment by marcoribeiroweb** [comment]
I upgraded to `2.21.5` and I still have a problem with 2 documents. 
Coincidence or not I have it in documents with the plugin Orderable Document List (https://www.sanity.io/plugins/orderable-document-list). 

![print](https://user-images.githubusercontent.com/9121280/137950679-19fb8d3c-c962-464c-9d87-e7a8e017dde9.png)

**Comment by rexxars** [comment]
Apologies for the incorrect data type on those documents - unfortunately you might have to revert to and older version or delete the document before it will allow you to edit it.

**Comment by leeuwd** [comment]
We're having the same issue:

> This document is of type page_collection and cannot be edited as page_download.

![image](https://user-images.githubusercontent.com/1755190/138092249-f9235f5e-b005-4449-ac50-c942915618b9.png)
![image](https://user-images.githubusercontent.com/1755190/138092292-6d27b84c-a606-45c7-b0d9-6b3872a0fe0a.png)

When inspecting the document, the type is clearly correct.

Not sure if the note from @rexxars actually fixes it: I can discard the changes and try again. Sometimes it does work after refreshing the page, and sometimes it doesn't. Any clue?

```
...
"@sanity/cli": "^2.20.0",
"@sanity/base": "^2.21.5",
"@sanity/components": "^2.14.0",
"@sanity/core": "^2.21.5",
 "@sanity/desk-tool": "^2.21.5",
```
