### ISSUE TITLE
Studio lags and cuts characters from typing as it autosaves

### ISSUE THREAD

**Issue by aidanm1999** [sanity-io/sanity#3185]
**Describe the bug**

When adding nested content into one document's portable text editor, the studio becomes laggy and unusable, causing some of the characters to be removed whilst typing, especially in tooltips. See video below in Screenshots.

**To Reproduce**

Steps to reproduce the behaviour:

*NB: If you want to skip the set-up process and install a minimal reproducible example, fork* [*aidanm1999/sanity-test*](https://github.com/aidanm1999/sanity-test)*, run `cd studio && npx sanity init` to configure as your own account and continue to step 6*

1. Create a new site from the [Portfolio with Gatsby](https://www.sanity.io/create?template=sanity-io%2Fsanity-template-gatsby-portfolio) template
2. Clone and cd into repo
3. Add an object to the schema called `columns` in `studio/schemas/documents/columns.js` :

```javascript
import React from "react";
import simplePortableText from "./simplePortableText";

export default {
    name: "columns",
    type: "object",
    title: "Columns",
    fields: [
        {
            ...simplePortableText,
            title: undefined,
            name: "left",
        },
        {
            ...simplePortableText,
            title: undefined,
            name: "right",
        },
    ],
    options: {
        editModal: "fullscreen",
        columns: 2,
    },
    preview: {
        component: () => (
            <div>
                <b>Columns</b>
                <p>Double click to open</p>
            </div>
        ),
    },
};
```

1. Edit the main schema in `studio/schemas/schema.js`  by importing `columns.js` and adding it to the `types` array:

```javascript
// First, we must import the schema creator
import createSchema from 'part:@sanity/base/schema-creator'

// Then import schema types from any plugins that might expose them
import schemaTypes from 'all:part:@sanity/base/schema-type'

// Document types
import category from './documents/category'
import person from './documents/person'
import sampleProject from './documents/sampleProject'
import siteSettings from './documents/siteSettings'

// Object types
import bioPortableText from './objects/bioPortableText'
import figure from './objects/figure'
import projectMember from './objects/projectMember'
import projectPortableText from './objects/projectPortableText'
import simplePortableText from './objects/simplePortableText'
import columns from './objects/columns'

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
  // We name our schema
  name: 'portfolio',
  // Then proceed to concatenate our our document type
  // to the ones provided by any plugins that are installed
  types: schemaTypes.concat([
    // When added to this list, object types can be used as
    // { type: 'typename' } in other document schemas
    bioPortableText,
    figure,
    projectMember,
    projectPortableText,
    simplePortableText,
    columns,
    // The following are document types which will appear
    // in the studio.
    category,
    person,
    sampleProject,
    siteSettings
  ])
})
```

1. Edit the schema of `simplePortableText` in `studio/schemas/objects/simplePortableText.js` . Below we are adding the `columns` type in the array and adding an external url object in the `annotations` :

```javascript
/**
 * This is the schema definition for the rich text fields used for
 * for this blog studio. When you import it in schemas.js it can be
 * reused in other parts of the studio with:
 *  {
 *    name: 'someName',
 *    title: 'Some title',
 *    type: 'simplePortableText'
 *  }
 */
export default {
  title: 'Portable Text',
  name: 'simplePortableText',
  type: 'array',
  of: [
    {
      title: 'Block',
      type: 'block',
      // Styles let you set what your user can mark up blocks with. These
      // corrensponds with HTML tags, but you can set any title or value
      // you want and decide how you want to deal with it where you want to
      // use your content.
      styles: [{title: 'Normal', value: 'normal'}],
      lists: [],
      // Marks let you mark up inline text in the block editor.
      marks: {
        // Decorators usually describe a single property – e.g. a typographic
        // preference or highlighting by editors.
        decorators: [
          {title: 'Strong', value: 'strong'},
          {title: 'Emphasis', value: 'em'},
          {title: 'Code', value: 'code'}
        ],
        // Annotations can be any object structure – e.g. a link or a footnote.
        annotations: [
          {
              name: "link",
              type: "object",
              title: "External link",
              fields: [
                  {
                      name: "href",
                      type: "url",
                      title: "URL",
                      validation: (Rule) =>
                          Rule.uri({
                              scheme: ["https", "mailto", "tel"],
                          }),
                  },
              ],
          },
        ]
      }
    },
    {
      type: 'columns'
    }
  ]
}
```

1. Run the studio `npm i && cd studio && npm run dev` and open in the [browser](https://localhost:3333/)
2. Navigate to `Desk > Sample projects > [A project] > Excerpt`
3. Repeat this process 3 times:
   1. In the portable text editor add 5 paragraphs of lorem ipsum
   2. Then add a column
   3. Double click into the column
   4. Open of the portable text editors

      *NB: The lorem ipsum is used to simulate real content & is used to increase the data size of the document (increasing lag)*

1. You should now be 3 portable texts deep. Add an external link by adding some text, highlighting it and clicking the link icon.
2. Open the tooltip and start typing a valid url. E.g. `https://www.sanity.io/docs/sanity-studio`
3. You should see the url being chopped around as the studio auto-saves. See video below for actual behaviour.

**Expected behaviour**

The text entered should not be deleted as the editor types.

**Screenshots**

During this recording, the following was typed: `https://www.google.com/search?` and nothing was deleted manually.

https://user-images.githubusercontent.com/36016925/157262570-c49dee27-774b-4b1e-b286-8179ce92f1af.mov

**Which versions of Sanity are you using?**

```Bash
@sanity/cli             2.27.3 (up to date)
@sanity/base            2.27.2 (up to date)
@sanity/cli             2.27.3 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.27.0 (up to date)
@sanity/dashboard       2.27.2 (up to date)
@sanity/default-layout  2.27.2 (up to date)
@sanity/default-login   2.27.0 (up to date)
@sanity/desk-tool       2.27.3 (up to date)
@sanity/structure       2.27.0 (up to date)
@sanity/studio-hints    2.24.1 (up to date)
```

**What operating system are you using?**

`MacOS 12.3`

**Which versions of Node.js / npm are you running?**

`npm 7.20.6`  `node v14.17.4`

**Comment by mlent** [comment]
Did you find a solution for this? I have the same issue anytime there are too many blocks in the content.

**Comment by aidanm1999** [comment]
No luck @mlent, we might try the developer preview of Sanity which might fix the issue

**Comment by AlejandroGarciaMaya** [comment]
Hey @aidanm1999 did you find a final solution for this? Same issue here.

**Comment by bjoerge** [comment]
If you're still on `v2` we did a series of performance fixes back in [v2.34.0](https://github.com/sanity-io/sanity/releases/tag/v2.34.0), so running `sanity upgrade` will likely improve things a lot for you all.

**Comment by aidanm1999** [comment]
Thanks @bjoerge, I upgraded packages to `2.35.0` and it has slightly improved. Less cursor jumping but I can still trigger easily. 

https://user-images.githubusercontent.com/36016925/200354301-cc66c2b8-5628-448a-9de7-7f1662294f6d.mov

**Comment by kmelve** [comment]
Hi! 

We are currently working on improving our workflows and follow-up on our open GitHub repository. In that work, we have decided to close most issues older than [the release of Sanity Studio v3](https://www.sanity.io/blog/sanity-studio-v3-simplified-yet-powerful-customization).

We value your feedback, so if this issue is still important to you and relevant for Sanity Studio v3, please search for relevant open issues. If you can’t find any, open a new one and link to relevant comments in this thread. For questions about how to do something, please post them in the [slack community](https://slack.sanity.io).

**Comment by ifeltsweet** [comment]
This should be reopened as it was solved only for portable editor, but not for string and text field inputs.

**Comment by notflip** [comment]
I still have this issue with custom objects that are inside an object. Is there a way to limit/throttle the autosave?

**Comment by eldoy** [comment]
Slow for me too, really annoying. Every keystroke is synced to the cloud or what's going on?

**Comment by notflip** [comment]
> Slow for me too, really annoying. Every keystroke is synced to the cloud or what's going on?

It seems like it, would be nice to add some debouncing, or disable it completely? I'm not sure if this is a feature request that's in progress.

**Comment by josh-padnick** [comment]
This issue has been resurrected at https://github.com/sanity-io/sanity/issues/7456. I think the following combination makes for a very unpleasant UX to the point of being unusable:

1. Auto-save on every single keystroke, and 
2. Each save takes more than 100ms

I think the Sanity folks need to address this by either:

1. Replacing "save on every keystroke" with a save button, or
2. Make every save lightning fast

It seems like most of the efforts right now are on (2), but can it ever get fast enough to provide the UX users expect?

**Comment by runeb** [comment]
@notflip Are you seeing typing lag, or cutting characters on saving? Last week we did release a version that improves responsiveness while typing, but I would like to hear more in case you are seeing characters being cut off.

**Comment by notflip** [comment]
@runeb It's while typing, I press a key and it takes 1 to 3 seconds for the character to appear. I haven't tested since your new release. I'll give it a shot, thanks

**Comment by eldoy** [comment]
@runeb It's a bit weird that you're asking us to show you, aren't you seeing it yourself? It gets worse the slower your internet connection is too. In think it's a really bad idea to sync every keystroke to the cloud. You should wait until the user has stopped typing at least.

```js
if (stoppedTyping) {
  sync()
}
```

**Comment by notflip** [comment]
> @runeb It's a bit weird that you're asking us to show you, aren't you seeing it yourself? It gets worse the slower your internet connection is too. In think it's a really bad idea to sync every keystroke to the cloud. You should wait until the user has stopped typing at least.
> 
> ```js
> if (stoppedTyping) {
>   sync()
> }
> ```

Exactly, or even a debounce of 10 seconds would be great, a sync of every keystroke is a bit too much.

**Comment by eldoy** [comment]
@runeb @bjoerge Ping! Your product is currently completely broken, how is this not a priority? Please fix asap!
