### ISSUE TITLE
Virtualized arrays of objects not rendering all items in 3.9.0

### ISSUE THREAD

**Issue by nervetattoo** [sanity-io/sanity#4396]
**Describe the bug**

Virtualized arrays of objects not rendering all items. The array in the screenshot has 4 elements. I can confirm all 4 being available in the studio by inspecting the document.
This works again when downgrading to 3.8.3

**To Reproduce**

In an array of objects that contain arrays of objects just open the popover to edit one element and look at the list of items.
For me this list is outside the viewport of the popover initially and I have to scroll down. This might affect the sizing logic perhaps.

**Expected behavior**

Should work like 3.8.3 with non-virtualized lists.

**Screenshots**

<img width="648" alt="Screenshot 2023-04-19 at 13 59 23" src="https://user-images.githubusercontent.com/45449/233068346-ea336354-f767-438a-9a36-6ede03588238.png">

**Which versions of Sanity are you using?**

sanity 3.9.0

**What operating system are you using?**

macOs ventura.
Arc browser, hence Chrome really.

**Which versions of Node.js / npm are you running?**

pnpm 7.26.3
node v18.13.0

**Comment by binoy14** [comment]
Hey @nervetattoo thanks for reporting the issue, are you able to share your schema and let us know if you have any customization to the array of objects list like custom components, etc?

**Comment by nervetattoo** [comment]
No custom components. Custom preview but just with strings, and I tried removing the previews.
The schema is complex and no I can't share it. I don't have the time to create a schema that verifies it this week at least, but the basics should be along these lines:

```ts
import {defineField, defineType} from 'sanity'

export const testDocument = defineType({
  name: 'test',
  title: 'Test',
  type: 'document',
  fields: [
    defineField({
      name: 'blocks',
      title: 'Blocks',
      type: 'array',
      of: [{ type: 'testBlock' }],
    }),
  ]
})

export const testBlock = defineType({
  name: 'testBlock',
  title: 'Test block',
  type: 'object',
  fields: [
    defineField({
      name: 'items',
      title: 'Items',
      type: 'array',
      of: [{ type: 'testElement' }],
      validation: Rule => Rule.required().min(1),
    }),
  ]
})

export const testElement = defineType({
  name: 'testElement',
  title: 'Test element',
  type: 'object',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: Rule => Rule.required(),
    }),
  ],
})
```

**Comment by alimovember** [comment]
We are also facing this same issue.
We have the same codebase in UAT and Prod, and we always deploy to latest sanity version.
Our UAT is running 3.9.0 and has this issue.
Our Prod is running 3.8.3 and does not have this issue.

Request to please fix this introduced bug quickly as it is blocking our production deployment, or making us blocked with older version of sanity.

Steps to reproduce:

For any field of type array of custom objects
Add >=3 of those items in the array
Now close the  window and reopen it
The first item/ sometimes first 2 items disappear as shown in ss below


![Screenshot 2023-04-19 at 2 03 39 pm](https://user-images.githubusercontent.com/54517907/233519946-139bcdc7-2cb8-420b-ae9e-f0423cd4180c.png)

**Comment by anthonysapp** [comment]
Still seeing this in 3.9.0

**Comment by deckchairlabs** [comment]
Also having the same issue

**Comment by anthonysapp** [comment]
Seems fixed now! Thanks!

**Comment by mrgnou** [comment]
I still have this bug on v3.11.5, which prevent us from upgrading from v3.8.3. Could we reopen this issue?

**Comment by binoy14** [comment]
@mrgnou could you please create a new issue and provide us with schema and any other information that would help us reproduce the issue
