### ISSUE TITLE
Ability to select multiple references for easier population of arrays of references

### ISSUE THREAD

**Issue by evenwestvang** [sanity-io/sanity#502]
Great suggestion from @burkhartt in #491 to populate arrays of references with multiple selects in reference picker. Needs design study to see how much rework would be involved.

**Comment by dylanjharris** [comment]
In our use case there are a "crazy amount of items" (to quote @burkhartt in #491 ). Checkboxes/multiselect wouldn't feel right. 

Feature request (which folds into this issue): ability to add references without having to close the dialog box.

CURRENTLY: click Add, then search, select, close dialog, click Add, search, select, close dialog, click Add....

AWESOME: click Add, then search, assign, search, assign, search, assign... close dialog.

<img width="807" alt="add-reference-to-array-dialog-box" src="https://user-images.githubusercontent.com/15899201/63290570-a96b3c80-c28f-11e9-9745-241818f62e1c.png">

**Comment by sjelfull** [comment]
@evenwestvang Have y'all done any design exploration on this yet? Care to share?

**Comment by c3controls** [comment]
Pinging @evenwestvang for any progress or design exploration on this? before trying to solve (temporarily) with custom input components.

Our use case is fairly unique but the desired feature is "simple": ability to add multiple references without closing the dialog box. 

My content person is populating data (there's _a lot_ of data) and if a document has 20 references, she has to Add+Search+Close+Add+Search+Close...20 times.... and it's painful to watch... let alone do. We can save many click-hours with a graceful solution.

If no progress has been made, can provide direction/example of custom input components involving the dialog/search? We can start from the [Unicorn Slider example](https://www.sanity.io/docs/custom-input-widgets), this [recipe snippet](https://github.com/sanity-io/sanity-recipes/blob/master/snippets/conditionalFieldsCustomInputComponent.js) and the [/components/src](https://github.com/sanity-io/sanity-recipes/blob/master/snippets/conditionalFieldsCustomInputComponent.js) but any headstart would be warmly embraced ❤️ 

Of course, a custom input component for this may be more trouble than it's worth, especially if you guys have something coming down the pipeline. 

Thanks!!

**Comment by dylanjharris** [comment]
Pinging @evenwestvang for any progress or design exploration on this? before trying to solve (temporarily) with custom input components.

Our use case is fairly unique but the desired feature is "simple": ability to add multiple references without closing the dialog box. 

My content person is populating data (there's _a lot_ of data) and if a document has 20 references, she has to Add+Search+Close+Add+Search+Close...20 times.... and it's painful to watch... let alone do. We can save many click-hours with a graceful solution.

If no progress has been made, can provide direction/example of custom input components involving the dialog/search? We can start from the [Unicorn Slider example](https://www.sanity.io/docs/custom-input-widgets), this [recipe snippet](https://github.com/sanity-io/sanity-recipes/blob/master/snippets/conditionalFieldsCustomInputComponent.js) and the [/components/src](https://github.com/sanity-io/sanity-recipes/blob/master/snippets/conditionalFieldsCustomInputComponent.js) but any headstart would be warmly embraced ❤️ 

Of course, a custom input component for this may be more trouble than it's worth, especially if you guys have something coming down the pipeline. 

Thanks!!

**Comment by evenwestvang** [comment]
Hi @dylanjharris – afraid we haven't had time to look at this yet. It's sitting in the box named `better reference handling` in a queue with some other items like `create references in place` and `better search for references`. I'm truly sorry though that the lack of a good solution here is wasting effort though.

I'll ping @mariuslundgard to see if he has any elegant ideas. The array component doesn't decompose well either and there may be quite some effort involved in making it do the things you want as well.

**Comment by c3controls** [comment]
Hi @evenwestvang - thank you for prompt response; we appreciate the transparency very much :)  

After a quickish glance at core I got the impression which you are confirming: modification more trouble than it's worth at this time. The solution we're leaning towards now is just a simple frontend for populating references, which would help in other ways too including better visualization, stats & data, conditions and error handling, using Vue over React... so... maybe a blessing in disguise that we aren't modifying Sanity studio here... necessity the mother of invention and all that... and we get to build a bespoke UI in Vue alongside our core project! 👍 

I'm still interested in any ideas Marius may suggest, time is the important factor here so any hacks/shortcuts/elegant solutions are still desirable. Thanks gang!

**Comment by dylanjharris** [comment]
Hi @evenwestvang - thank you for prompt response; we appreciate the transparency very much :)  

After a quickish glance at core I got the impression which you are confirming: modification more trouble than it's worth at this time. The solution we're leaning towards now is just a simple frontend for populating references, which would help in other ways too including better visualization, stats & data, conditions and error handling, using Vue over React... so... maybe a blessing in disguise that we aren't modifying Sanity studio here... necessity the mother of invention and all that... and we get to build a bespoke UI in Vue alongside our core project! 👍 

I'm still interested in any ideas Marius may suggest, time is the important factor here so any hacks/shortcuts/elegant solutions are still desirable. Thanks gang!

**Comment by Igli7** [comment]
any update on this?

**Comment by adrienpicard** [comment]
+1 any update or pointers would be appreciated.

Is this on the table for v3 perhaps? Thank you!

**Comment by HaraldSigvartsen** [comment]
Looking for a update on this aswell.

**Comment by toddpadwick** [comment]
This would also be really useful for arrays of images/files too

**Comment by felipeorlando** [comment]
4 years and this is not done yet? 🤦‍♂️

**Comment by kmelve** [comment]
This is partly solved with the new array of references behavior that was introduced here: https://github.com/sanity-io/sanity/pull/3767

Closing this for now. 

<img width="639" alt="CleanShot 2023-01-12 at 14 53 35@2x" src="https://user-images.githubusercontent.com/1131579/212084949-6196cc5d-128b-42c3-8889-d4487b9438dd.png">

**Comment by ryanleichty** [comment]
Looking for other solutions to the problems mentioned above. The `add + click + select` combo is a bit tedious, especially when there's only a few reference documents to select from (in my case 7 which will likely not increase). It would be great if:

1. You could select multiple references without closing the dialog
2. It included additional layout options
   - Checkboxes or radios (with the assumption that you can't reorder items)

I know that you can create custom components, but I'm trying to build a demo for a site of ours to convince the team to switch from Craft CMS to Sanity, and spinning something up quick is key at the moment.

Is there anything I'm missing here or other ways to structure things?

**Comment by toddpadwick** [comment]
Hi @kmelve I agree with @ryanleichty, that this does not solve the problem. 
This is how selecting references works on most other CMSs:
As you can see, drastically easier to select multiple references than in Sanity.

https://github.com/sanity-io/sanity/assets/36191462/21705f7d-69e1-419f-92d3-84185a6c375d

**Comment by sabir-Hussain** [comment]
Any update on this?

**Comment by ryanleichty** [comment]
Apparently coming back to this 2 years later to find the same solution 😅

I'm catching up with all of the Sanity updates, but any update or solution to this problem?
