### ISSUE TITLE
Documents without a `title` field are not displayed in document lists or reference fields within the studio as of v3.38.0

### ISSUE THREAD

**Issue by bendesilva** [sanity-io/sanity#6398]
**Describe the bug**

A document type within my schema does not have a `title` field, and instead relies on preview to generate a title from other field values. After upgrading to v3.38.0 these documents are not visible in their document list or any reference fields. Downgrading to v3.37.2 results in the documents being visible again. I could demonstrate the issue by adding a `title` field to the document schema and adding values to those fields on some documents whilst on v.3.37.2, upon upgrading to v3.38.0 again, those documents were visible in the document list, whilst the documents that I didn't add a `title` value to were still not visible. 

**To Reproduce**

1. Downgrade to Sanity v3.37.2
2. Add a document type to the schema without a `title` field and any other field to ensure it can be published
3. Create a document
4. Upgrade to Sanity v3.38.0
5. The document is no longer visible in the document list

**Expected behavior**

Documents are visible in document lists and reference fields regardless of whether they have a title or not. Please note that these documents were always visible in the Vision tool, and existing references were unaffected.

**Which versions of Sanity are you using?**

3.38.0

**What operating system are you using?**

MacOS 13.2.1

**Which versions of Node.js / npm are you running?**

NPM 10.2.4
Node.js v20.11.0

**Additional context**

Sanity is running on a route within Next.js via `yarn dev`

**Comment by ricokahler** [comment]
Hello @bendesilva!

This may be related to the new search strategy we just rolled out in v3.38.0. Can you try enabling the legacy search and seeing if that fixes your issue?

```ts
import { defineConfig } from 'sanity'

export default defineConfig({
  name: 'default',
  title: 'Test Studio',
  search: {
    enableLegacySearch: true,
  },
  // ...
})
```

**Comment by ricokahler** [comment]
Can you provide a small schema that could help us reproduce this issue?

**Comment by bendesilva** [comment]
Thanks Rico, I'll look to test your solution and provide a small schema to reproduce the issue. Currently on a project which this came up as a blocking issue, so I have assigned titles in the interim to those affected documents. Will come back asap.

**Comment by ricokahler** [comment]
Hi @bendesilva did re-enabling the legacy search resolve your issue? Is this issue still valid?

**Comment by bendesilva** [comment]
Hi @ricokahler, thanks for your patience! Haven't had a chance to do further testing or put together a reduced schema until now. 

I've replicated the issue I was experiencing, it's also present on 3.39.0, but as suggested the legacy search setting did indeed fix the issue and all documents appear within the document list. It seems that it only occurs when the preview component uses expanded references.

https://github.com/bendesilva/sanity-studio-test

For the reduced test case I have adapted the default blog schema provided when scaffolding a new studio. I have adapted the `author` schema to have two fields; `category` and `name`, `category` is a reference field to the `category` document type and `name` is a string field. The preview title uses `category.title` and the subtitle uses `name`. If you publish a document with the `category` field set only, the document will not appear in the list, if you set both the `category` reference and `name` then it will appear.

Setting `enableLegacySearch` to `true` reveals all documents as expected.

For reference my original use case was for a colour palette document type, each document has a series of reference fields to predefined colour swatch documents (i.e. background, foreground, highlight). The preview component would generate a title from the colour swatch titles and values. In the end I just gave each swatch a title to get around this issue.

**Comment by juice49** [comment]
Hey @bendesilva. Thank you for providing those details! We've identified an issue causing documents to disappear from document lists if they contain no searchable paths. This is why your documents disappear when they only contain a reference, but appear if you add a string field.

We will fix this in the backend, so you shouldn't need to update Studio for things to begin working. We'll share an update here as soon as that fix is in place.

**Comment by juice49** [comment]
We've released a backend fix for this issue now. @bendesilva, please let us know if you experience any further issues, and I'm sorry for the trouble this caused you.

**Comment by alexeygolev** [comment]
I had the same problem and the fix didn't fix it. But it might be something else. I checked my network tab to see the response from the search query and, although the `matchScore` field for the document I'm searching for is the highest, it's somewhere in the middle of the results list in UI. So it seems like the search works correctly at the backend but the "Best match" sorting is not taking the rankingInfo into the account

**Comment by bendesilva** [comment]
@juice49 Thanks for the update, looks like it's fixed the issue of documents not appearing in lists or when selecting a reference, so that's great. Those documents aren't being surfaced in the global studio search, nor am I able to search for the document in a reference field (I can select it from the dropdown), but I'm assuming that's because the preview component for those documents is expanding the reference's title and the document itself doesn't have any indexable data.

**Comment by juice49** [comment]
@bendesilva Excellent! Thank you for confirming.

> Those documents aren't being surfaced in the global studio search, nor am I able to search for the document in a reference field (I can select it from the dropdown), but I'm assuming that's because the preview component for those documents are expanding a reference's title to use as its own, and the document itself doesn't have any indexable data.

If I understand correctly, your document contains only references, and you're attempting to search for it based on a field that appears in one of those _referenced_ document. I'm afraid that is not something supported either before or after the most recent search update.

**Comment by bendesilva** [comment]
@juice49 That's right, and this is really an aside to the now resolved issue. But, using the example studio I provided, the preview component `title` property of a `category` document uses the title of a referenced `author` document. However when you have a reference field to a `category` document (as the `post` document type does), you can see those documents in the reference dropdown, but when searching for a term appearing in the preview, those documents aren't returned. I understand why this is, but the UX feels a bit jarring and could be confusing to some editors, as it feels as though the reference search input would be filtering the document list you'd already seen.

Selecting a document from a reference field:
<img width="628" alt="Screenshot 2024-04-26 at 14 47 06" src="https://github.com/sanity-io/sanity/assets/5658721/ed711fe6-f9af-4907-bf57-ada280ccd005">

Typing in a term which one would expect to return a result:
<img width="628" alt="Screenshot 2024-04-26 at 14 47 13" src="https://github.com/sanity-io/sanity/assets/5658721/46828ecc-53c0-4f5f-bae8-eabb5e6a6579">
