### ISSUE TITLE
Schema extract always assumes inline referenced documents are References

### ISSUE THREAD

**Issue by obrassard** [sanity-io/sanity#6913]
I have a document containing an array field, mixing different types of reference and objects : 
```js
defineField({
      name: 'modules',
      title: 'Modules',
      type: 'array',
      group: 'editorial',
      of: [
        { type: 'reference', name: 'ref.module.fullWidthTextBlock', to: [{ type: 'module.fullWidthTextBlock' }] },
        { type: 'reference', name: 'ref.module.textWithImageBlock', to: [{ type: 'module.textWithImageBlock' }] },
        { type: 'reference', name: 'ref.module.fullWidthImageBlock', to: [{ type: 'module.fullWidthImageBlock' }] },
        // ... Other reference types here
        { type: 'module.instagramBlock' }, // Object
      ],
    }),
```

We fetch this data using a query like this : 
```ts
export const SanityProductModulesQuery = groq`
*[_type == 'product' && store.slug.current == $handle][0].modules[] {
    _type == 'module.instagramBlock' => {
        _key,
        _type,
        "title": title[$lang],
        category,
    },
    _type == 'ref.module.textWithImageBlock' => @ -> {
        _type,
        "_key": ^._key,
        "subTitle": subTitle[$lang],
        "title": title[$lang],
        "body": body[$lang],
        color,
        orientation
    },
    _type == 'ref.module.fullWidthTextBlock' => @ -> {
        _type,
        "_key": ^._key,
        "title": title[$lang],
        "body": body[$lang],
    }
}
`;
```

The Generated Types for this query is incorrect  : 
```ts
export type SanityProductModulesQueryResult = Array<
  | {
      _key: string;
      _type: 'module.instagramBlock';
      title: Array<{
        _type: 'localizedString';
        fr: string;
        en: string;
      }>;
      category: string;
    }
  | {} //We should have other types here, for referenced items
> | null;
```

The query itself work properly when tested in the vision plugin.

---

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.45.0 (up to date)
@sanity/asset-utils            1.3.0 (up to date)
@sanity/color-input            3.1.1 (up to date)
@sanity/eslint-config-studio   3.0.1 (latest: 4.0.0)
@sanity/icons                  3.2.0 (up to date)
@sanity/language-filter        4.0.2 (up to date)
@sanity/ui                     2.3.1 (latest: 2.3.3)
@sanity/vision                3.45.0 (up to date)
sanity                        3.45.0 (up to date)
```

**What operating system are you using?**
Mac OS 14.5 / Chrome

**Which versions of Node.js / npm are you running?**

NPM : 9.8.1
NODE : v18.18.2

**Comment by obrassard** [comment]
I thought this issue might be related to https://github.com/sanity-io/sanity/issues/6555 so I removed the ` => @` to test like this : 

```ts
export const SanityProductModulesQuery = groq`
*[_type == 'product' && store.slug.current == $handle][0].modules[] {
    _type == 'module.instagramBlock' => {
        _key,
        _type,
        "title": title[$lang],
        category,
    },
    _type == 'ref.module.textWithImageBlock' => {
        _type,
        _key,
        _ref,
    },
    _type == 'ref.module.fullWidthTextBlock' => {
        _type,
        _key,
        _ref,
    }
}
`;
```

However, the result stays the same, and the generated Array type only contains the correct type for `module.instagramBlock` (which is the only possible object in our schema). 

I have the impression that the problem has more to do with the fact that we have several references with different names, and the parser doesn't resolve properly those custom `_type` (eg `_type == 'ref.module.textWithImageBlock'`)

**Comment by sgulseth** [comment]
Hi! Can you try with the latest version we just released? [v3.49.0](https://github.com/sanity-io/sanity/releases/tag/v3.49.0)

**Comment by obrassard** [comment]
Hi @sgulseth, unfortunately the issue persist event after upgrading to v3.49.0 : 

```
⚡npx sanity versions
@sanity/cli (global)          3.49.0 (up to date)
@sanity/asset-utils            1.3.0 (up to date)
@sanity/color-input            3.1.1 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/icons                  3.2.0 (up to date)
@sanity/language-filter        4.0.2 (up to date)
@sanity/ui                     2.6.1 (up to date)
@sanity/vision                3.49.0 (up to date)
sanity                        3.49.0 (up to date)
```

**Comment by obrassard** [comment]
@sgulseth We noticed another issue that might be related to this one.

For context, we have different `document` types that represent pages sections (or modules) of our website. These sections are referenced in different other content type. 

However, in one particular case we wanted to use some of those section schema without them being referenced. For this case, we've been using our `document` types as if they were `objects`, in an array like this : 

```
defineField({
      title: 'Page modules',
      name: 'modules',
      description: 'Editorial sections displayed on the page',
      type: 'array',
      of: [
        { type: 'module.textWithImage' },
        { type: 'module.carousel' },
        { type: 'module.accordion' },
      ],
    }),
```
Where all "modules" are`document` types. This work's fine in the editor and the API, however the TypeGen doesn't seem to understand some query properly. For instance, when using conditional and projections like the following,  the resulting type is `Array<{}> | null`.

```
    _type == "module.textWithImage" => {
        _type,
        name,
    }
```
It is noteworthy that once the type of `blogArticle` is changed from `document` to `object`, the type is generated properly.

**Comment by sgulseth** [comment]
Thanks for letting us know, @obrassard! I suspect this is related to https://github.com/sanity-io/groq-js/pull/250 as we weren't handling splatting over optional fields very well.

**Comment by obrassard** [comment]
@sgulseth Unfortunately adding a required validation on the modules field **did not solve the issue**.

---

To help you diagnose the issue, I created a sample repository here : https://github.com/obrassard/sanity-typegen-issues containing an example of the two problems mentioned here.

In the example you'll find 4 types of documents (two types of page [`modules`](https://github.com/obrassard/sanity-typegen-issues/tree/main/schemaTypes/documents/modules)), a [`product`](https://github.com/obrassard/sanity-typegen-issues/blob/main/schemaTypes/documents/product.tsx) document and an [`article`](https://github.com/obrassard/sanity-typegen-issues/blob/main/schemaTypes/documents/article.ts) document.

- In `product`, modules documents are included as "named" references.
- In `article`, modules documents are included as if they where objects (no references)

There is two different queries in the [groq](https://github.com/obrassard/sanity-typegen-issues/tree/main/groq) directory that were used to fetch an article or a product based on their slug. In both case the [generated types](https://github.com/obrassard/sanity-typegen-issues/blob/main/types/sanity-groq.generated.d.ts) are incorrect for the `modules` field : 

<img width="628" alt="Capture d’écran, le 2024-07-25 à 09 57 30" src="https://github.com/user-attachments/assets/c49ac420-f63e-48b3-82d3-c1cb52c93f54">


Note that you can use `npm run codegen` to regenerate the types in this project.

**Comment by obrassard** [comment]
On other branches of the example repo, you may also notice how

1. Changing the type of both modules documents to `object` "fixes" the generated type for the `article` document : https://github.com/obrassard/sanity-typegen-issues/compare/main...article-objects

3. Changing how we define the references in the `product` document, fixes generation of the `product` document : https://github.com/obrassard/sanity-typegen-issues/compare/main...product-reference

**Comment by sgulseth** [comment]
Ah, they are referencing another document. Then you need to dereference the referenced document. So instead of doing:
```
modules[] {
...
}

do:
```
modules[]-> {
...
```

**Comment by obrassard** [comment]
@sgulseth 

In the case of the `article` document, the modules are **not** referenced, as the field is defined as such : 

```ts
defineField({
    name: 'modules',
    type: 'array',
    validation: Rule => Rule.required(),
    // No reference here
    of: [
      { type: 'module.textBlock' },
      { type: 'module.textImageBlock' },
    ],
  })
````

For the `Product` document, they are indeed referenced, however the query we wrote **already include the dereferencing operator** for each ref : 

<img width="602" alt="Capture d’écran, le 2024-07-25 à 15 19 00" src="https://github.com/user-attachments/assets/ebed84e3-c759-4c7c-bdfe-3aed9c9c80bf">

**Comment by sgulseth** [comment]
I see. The problem is still similar: Inside of `modules[]` the object look something like: 
```
{
  _key: 'someKey',
  _type: 'reference',
  _ref: '...'
  _weak: true/false
}
```

So you can't compare _type to the referenced document type. What you want is something like:

```
 modules[] {
      _key,
      ...(@-> {
		_type,
        _type == 'module.textBlock' => {
          "title": ${localized('title')},
          "body": ${localized('body')},
        },
        _type == 'module.textImageBlock' => {
          "subTitle": ${localized('subTitle')},
          "title": ${localized('title')},
          "body": ${localized('body')},
          image
        }
    })
  }
```

here we dereference `@` before comparing `_type`.

Running this locally gives me:

```
export type SanityProductModulesQueryResult = {
  title: string
  slug: string
  modules: Array<
    | {
        _key: string
        _type: 'module.textBlock'
        title: string
        body: string
      }
    | {
        _key: string
        _type: 'module.textImageBlock'
        subTitle: string | null
        title: string
        body: string
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
  >
} | null
```

**Comment by obrassard** [comment]
Thanks @sgulseth I hadn't thought of writing the product query like that, but indeed by modifying the query you say, it works as expected. Note, however, that the initial query (with `_type == 'ref.module.textBlock' => @ -> {`) **did worked as expected** in the API and the Vision plugin (therefore I would have expected the TypeGen plugin to be able to parse it).

On the other hand, it doesn't solve the second case (BlogArticleQuery) where there is no reference.

**Comment by sgulseth** [comment]
np!

> did work as expected in the API and the Vision plugin

That is weird! That might indicate that the schema model and your content model isn't 1-1

---

Is the reproduction repo you pushed up to date with what you have that doens't work? `SanityBlogArticleQueryResult` is correct when I do: `modules[]-> {`

**Comment by obrassard** [comment]
> Is the reproduction repo you pushed up to date with what you have that doens't work? `SanityBlogArticleQueryResult` is correct when I do: `modules[]-> {`

Sorry for the confusion, actually adding the `->` operator does generate the correct type for SanityBlogArticleQueryResult, however the query itself does not work as you can see below : 

**Before**
<img width="1458" alt="Capture d’écran, le 2024-07-25 à 16 05 55" src="https://github.com/user-attachments/assets/2962a85e-f3a9-4ce8-ad69-bec6153d87e7">

**After**
<img width="1473" alt="Capture d’écran, le 2024-07-25 à 16 05 45" src="https://github.com/user-attachments/assets/7b75a16f-2083-41d2-9352-6c58c6e284f0">

It does not work, because unlike the other query the modules are not referenced (even tho they are declared as `documents` they are use as if they were `objects`)

**Comment by obrassard** [comment]
@sgulseth While testing the new query with `...(@-> {` on our real website, I noticed another issue.

If you have an array mixing references and non-refeferenced objects, the result is not correct. 

I updated the example repo, and as you can see [here](https://github.com/obrassard/sanity-typegen-issues/commit/9aa1960e4b4cb7ae84c41132115865d85af0333c) the `module.objectBlock` has been added to the product's `modules[]` field. This is not a reference.

When generating the type, we got : 

```
modules: Array<
    | {
        _key: string
        _type: 'module.textBlock'
       ...
      }
    | {
        _key: string
        _type: 'module.textImageBlock'
        ...
      }
    | unknown
  >
```

But we should have :
```
modules: Array<
    | {
        _key: string
        _type: 'module.textBlock'
       ...
      }
    | {
        _key: string
        _type: 'module.textImageBlock'
        ...
      }
    | {
        _key: string
        _type: 'module.objectBlock'
       ...
      }
  >
```

**Comment by sgulseth** [comment]
> Sorry for the confusion, actually adding the -> operator does generate the correct type for SanityBlogArticleQueryResult, however the query itself does not work as you can see below :

From what I can tell based on your vision result is that your schema has diverged from the content. In your schema it's references, but in the content lake it's stored inline.


> If you have an array mixing references and non-refeferenced objects, the result is not correct.

yes, then you also need to compare the types inside the modules container. Ie something like:

```
 modules[] {
        _key,
        _type == 'module.objectBlock' => {
            _type,
            "title": ${localized('title')},
        },
        _type == 'reference' => {
          ...(@ -> {
              _type == 'module.textBlock' => {
                  _type,
                  "title": ${localized('title')},
                  "body": ${localized('body')},
              },
              _type == 'module.textImageBlock' =>  {
                  _type,
                  "subTitle": ${localized('subTitle')},
                  "title": ${localized('title')},
                  "body": ${localized('body')},
                  image
              },
          })
        }
    }
```

generates:
```typescript
modules: Array<
    | {
        _key: string
        _type: 'module.objectBlock'
        title: string
      }
    | {
        _key: string
        _type: 'module.textBlock'
        title: string
        body: string
      }
    | {
        _key: string
        _type: 'module.textImageBlock'
        subTitle: string | null
        title: string
        body: string
        image: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
      }
  >
```

**Comment by sgulseth** [comment]
Ah. I see, you are using a document as an inline reference. This looks to be a bug in the schema extrat, yes :)
