### ISSUE TITLE
Not possible to edit drafts when liveEdit: true

### ISSUE THREAD

**Issue by bjoerge** [sanity-io/sanity#886]
If you for some reason has a draft document and `liveEdit` enabled for the document type, it's currently not possible to edit the document.

I suggest we handle this by displaying a publish button together with a warning saying the document has to be published before it can be edited.

**Comment by vicbergquist** [comment]
According to the internal tracker this has been fixed. Closing.

**Comment by stipsan** [comment]
Re-opening as this is still an issue and it's pretty terrible when it happens (I wasted hours today thinking we had a regression bug in Presentation Tool):

https://github.com/user-attachments/assets/3be52200-1c2a-463a-836f-e2b57dc26712
