### ISSUE TITLE
@sanity/codegen crashes on typegen with "operator undefined" error

### ISSUE THREAD

**Issue by yusifaliyevpro** [sanity-io/sanity#9870]
**Describe the bug**
When running `pnpm typegen`, the command fails with a `TypeError: Property operator expected type of string but got undefined`.
This error seems to come from the `@sanity/codegen` package during the `generateKnownTypes` step.

**To Reproduce**

1. Run `pnpm typegen` script, which includes:
   `sanity schema extract --enforce-required-fields --path=./src/sanity/extract.json && sanity typegen generate`
2. Wait for type generation to start
3. The error appears in the terminal and the process exits with code 1

**Expected behavior**
I expected the type generation to complete successfully and generate correct TypeScript types for my schema.

**Error log**

```
$ pnpm typegen

> yusifaliyevpro@1.0.0 typegen C:\Users\yusif\Documents\CodeProjects\YusifAliyevPro
> sanity schema extract --enforce-required-fields  --path=./src/sanity/extract.json && sanity typegen generate && rm ./src/sanity/extract.json


   ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
   │                                                                                                               │
   │   The `sanity` package is moving to v4 on July 15 and will require Node.js 20+.                               │
   │   Learn what this means for your apps at https://www.sanity.io/blog/a-major-version-bump-for-a-minor-reason   │
   │                                                                                                               │
   └───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

✓ Extracted schema to ./src/sanity/extract.json with enforced required fields

   ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
   │                                                                                                               │
   │   The `sanity` package is moving to v4 on July 15 and will require Node.js 20+.                               │
   │   Learn what this means for your apps at https://www.sanity.io/blog/a-major-version-bump-for-a-minor-reason   │
   │                                                                                                               │
   └───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

⠼ Generating types(node:20232) Warning: Closing file descriptor 3 on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20232) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
⠹ Generating types
TypeError: Property operator expected type of string but got undefined
    at Object.validate (C:/Users/yusif/Documents/CodeProjects/YusifAliyevPro/node_modules/.pnpm/@babel+types@7.28.0/node_modules/@babel/types/lib/definitions/utils.js:146:11)
    at validateInternal (C:/Users/yusif/Documents/CodeProjects/YusifAliyevPro/node_modules/.pnpm/@babel+types@7.28.0/node_modules/@babel/types/lib/validators/validate.js:22:9)
    at Object.tsTypeOperator (C:/Users/yusif/Documents/CodeProjects/YusifAliyevPro/node_modules/.pnpm/@babel+types@7.28.0/node_modules/@babel/types/lib/builders/generated/lowercase.js:2587:3)
    at TypeGenerator.generateKnownTypes (C:/Users/yusif/Documents/CodeProjects/YusifAliyevPro/node_modules/.pnpm/@sanity+codegen@3.96.0/node_modules/@sanity/codegen/lib/index.js:580:39)
    at main (C:/Users/yusif/Documents/CodeProjects/YusifAliyevPro/node_modules/.pnpm/@sanity+cli@3.96.0_@types+n_d9a15370aa3afddaee26a611898bdba7/node_modules/@sanity/cli/lib/workers/typegenGenerate.js:13:186)
⠇ Generating types ELIFECYCLE  Command failed with exit code 1.
```

**Which versions of Sanity are you using?**

```
@sanity/cli: 3.96.0  
@sanity/codegen: 3.96.0
```

**What operating system are you using?**
Windows 11

**Which versions of Node.js / npm are you running?**

```
pnpm: 10.12.4
node: v22.16.0
```

**Comment by yusifaliyevpro** [comment]
Maybe it is becuase of @sanity/cli. It happens after upgrading to version 3.96.0

**Comment by SkinnyAG** [comment]
I am also facing the same issue. Created a simple project using create-sanity and followed the commands specified in the "Generating types from your schema" course. The schema extraction is seemingly fine, but the error occurs when executing typegen generate.

**Comment by ajaymenon0** [comment]
Upgrading to `3.96.0` for `sanity` and `@sanity/vision` led me to this issue.
Downgrading works, but can't deploy to Sanity cloud without upgrading.

[edit: apologies, I realised I can opt out to deploying without upgrading]

**Comment by yusifaliyevpro** [comment]
The main cause is @sanity/cli i think

**Comment by Jamiewarb** [comment]
Here's a **minimal reproduction** repo for debugging: https://github.com/hex-digital/typegen-error-reproduction

The problem continues to occur no matter how far I downgrade `sanity` (tested to 3.80.0) (EDIT: this may be a red herring as noted below by others, as it may be I was still getting a later version of `@babel/types`)

<img width="1248" alt="Image" src="https://github.com/user-attachments/assets/ea9875c2-0c1a-4df0-8dde-78656551fcaa" />

### Workaround

As noted by @phucnguyen035 and @largis21 (thanks folks!), adding the below workaround to package.json resolves the issue

```
  "pnpm": {
    "overrides": {
      "@babel/types": "7.27.7"
    }
  }
```

<img width="834" alt="Image" src="https://github.com/user-attachments/assets/d5e89109-2b0f-4ad6-86d8-c88413d4c673" />

**Comment by SkinnyAG** [comment]
I am also struggling to get it to work when downgrading, although im probably missing something somewhere. I tried to downgrade both sanity and vision/sanity to 3.92.0 as this is the version used in a different project of mine. Could @ajaymenon0 provide what you specifically downgraded and to which versions?

**Comment by sanderkorf** [comment]
Issue also occurs here, can't get it fixed with downgrading unfortunately.

**Comment by CharlesOuverleaux** [comment]
Same issue here, it stopped working after upgrading to 3.96! It doesn't solve the error by downgrading back to 3.95.

**Comment by ajaymenon0** [comment]
@SkinnyAG 
Had to downgrade to 3.95 and then clear `node modules` and `package-lock.json` to get it working.
When it gets installed with legacy peer deps, package lock doesn't play along well.

**Comment by yusifaliyevpro** [comment]
Of course, Downgrading works, but need to solve by PR. I couldn't find anything related to this issue on latest changelog. A Sanity developer must solve this issue.

**Comment by arturmeinzer** [comment]
Same problem here, just noticed it after upgrading sanity

**Comment by marlonmarcello** [comment]
Just bumped into this one. Downgrading worked. Hopefully the team will push a fix soon 🙏

**Comment by phucnguyen035** [comment]
I also run into this issue ~and downgrading also doesn't fix it~ (correction: Downgrading works as long as `package-lock.json` does not bump `@babel/types` package version). After investigating I found that the issue could be coming from a recent change in `@babel/types` package ([version 2.8.0](https://github.com/babel/babel/releases/tag/v7.28.0), specifically this PR https://github.com/babel/babel/pull/17009). Downgrading that package fixes the issue for me.

```jsonc
  // package.json
  "overrides": {
    "@babel/types": "7.27.7"
  }
```

**Comment by largis21** [comment]
Thanks @phucnguyen035 

For pnpm users, use "pnpm.overrides" in root package.json
```json
{
  "name": "root-package.json",
  "packageManager": "pnpm@10.11.0",
  "pnpm": {
    "overrides": {
      "@babel/types": "7.27.7"
    }
  }
}
```

**Comment by SkinnyAG** [comment]
The following seems to work for Yarn v1 in the root package.json
```
  "resolutions": {
    "@babel/types": "7.27.7"
  },
```

**Comment by kaitcham** [comment]
Can someone guide me through how to fix this issue, I even tried to overrides the "@babel/types": "7.27.7" but I'm still facing the same issue.

**Comment by martinse** [comment]
Try running `pnpm sanity` or `npx sanity`. I had the issue when running `pnpm dlx sanity` that it didn't pick up the local overrides as it always used what is defined in the global installation.

**Comment by kaitcham** [comment]
Thanks @martinse

**Comment by nuotsu** [comment]
for `npm` users the command is
```sh
npm pkg set overrides."@babel/types"="7.27.7"
npm i
```

then typegen worked 😛

**Comment by sgulseth** [comment]
Hi, thanks for reporting. We are looking into fixing this, the issue seems to be with `@babel/types@7.28` - a mitigation until the fix is released is to pin `@babel/types` to an earlier version like mentioned above

**Comment by diligent-katja** [comment]
If overrides for babel types doesn't work, try to use node v20.18.

**Comment by jeevan-vaishnav** [comment]
just overrides the babel/types and it worked for me ,    

"pnpm": {
    "overrides": {
      "@babel/types": "7.27.7"
    }
  }

happy moment : 
✓ Generated TypeScript types for 19 schema types and 6 GROQ queries in 6 files into: ./sanity.types.ts

**Comment by pedrobonamin** [comment]
Thank you for reporting this, a fix is going out today as part of v3.97.0

**Comment by Jamiewarb** [comment]
Looks like it's been released now. Thanks folks!

https://www.sanity.io/docs/changelog/dafaceb1-4859-44b0-a4eb-0d29e9de07ba

**Comment by yusifaliyevpro** [comment]
Thanks
